# Generated by Django 5.1.13 on 2026-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_add_values_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='type',
            field=models.CharField(choices=[('post', 'Текст'), ('intro', '#intro'), ('link', 'Ссылка'), ('question', 'Вопрос'), ('idea', 'Идея'), ('project', 'Проект'), ('event', 'Событие'), ('battle', 'Батл'), ('weekly_digest', 'Журнал сообщества'), ('guide', 'Путеводитель'), ('thread', 'Тред'), ('docs', 'Доки'), ('job', 'Вакансия')], db_index=True, default='post', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Текст'), ('intro', '#intro'), ('link', 'Ссылка'), ('question', 'Вопрос'), ('idea', 'Идея'), ('project', 'Проект'), ('event', 'Событие'), ('battle', 'Батл'), ('weekly_digest', 'Журнал сообщества'), ('guide', 'Путеводитель'), ('thread', 'Тред'), ('docs', 'Доки'), ('job', 'Вакансия')], db_index=True, default='post', max_length=32),
        ),
    ]
