# Generated by Django 5.1.13 on 2026-06-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_alter_historicalpost_type_alter_post_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPost',
        ),
    ]
