# Generated by Django 5.1.13 on 2026-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_year_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_platform_type',
            field=models.CharField(choices=[('direct', 'Direct')], default='direct', max_length=128),
        ),
    ]
