# Generated by Django 5.1.13 on 2026-06-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_user_email_digest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership_platform_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership_platform_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership_started_at',
        ),
    ]
