# Generated by Django 5.1.13 on 2026-06-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_user_stripe_id'),
        ('users', '0039_remove_user_balance_and_more'),
    ]

    operations = [
    ]
