# Generated by Django 5.1.13 on 2026-01-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_alter_room_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-chat_member_count", "index"]},
        ),
    ]
