x-app-env: &app-env
  MODE: dev
  DEBUG: "true"
  PYTHONUNBUFFERED: "1"
  PYTHONWARNINGS: ignore
  POSTGRES_DB: nes_club
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  REDIS_DB: "0"
  REDIS_HOST: redis

x-app-base: &app-base
  build:
    context: .
  environment:
    <<: *app-env
  volumes:
    - .:/app:delegated
  restart: always
  depends_on:
    - postgres
    - redis

services:
  club_app:
    <<: *app-base
    container_name: club_app
    command: make docker-run-dev
    depends_on:
      - postgres
      - redis
      - queue
      - webpack
    ports:
      - "8000:8000"

  queue:
    <<: *app-base
    command: make docker-run-queue

  postgres:
    image: postgres:14
    container_name: club_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nes_club
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  webpack:
    image: node:20-slim
    command: sh -c "npm ci && npm run watch"
    environment:
      BROWSERSLIST_IGNORE_OLD_DATA: "1"
    volumes:
      - .:/app:delegated
    working_dir: /app/frontend

  bot:
    <<: *app-base
    command: make docker-run-bot
    restart: on-failure

  helpdeskbot:
    <<: *app-base
    command: make docker-run-helpdeskbot
    restart: on-failure

volumes:
  postgres_data:
