# Generated by Django 5.1.13 on 2026-06-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_alter_comment_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalComment',
        ),
    ]
