# Generated by Django 5.1.13 on 2026-01-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clickers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="click",
            options={"ordering": ["-created_at"]},
        ),
    ]
