# Generated by Django 5.1.13 on 2026-03-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickers', '0002_alter_click_options'),
        ('users', '0037_alter_user_membership_platform_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='users.user'),
        ),
    ]
