# Generated by Django 3.2.13 on 2024-12-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='status',
        ),
    ]
